/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostType = IDL.Variant({
  'reel' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const CreatePostRequest = IDL.Record({
  'content' : IDL.Text,
  'type' : PostType,
  'reelUrl' : IDL.Text,
  'imageUrl' : IDL.Text,
  'caption' : IDL.Text,
});
export const PostId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Post = IDL.Record({
  'id' : PostId,
  'likeCount' : IDL.Nat,
  'content' : IDL.Text,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'type' : PostType,
  'reelUrl' : IDL.Text,
  'shareCount' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'caption' : IDL.Text,
  'commentCount' : IDL.Nat,
});
export const StoryId = IDL.Nat;
export const Story = IDL.Record({
  'id' : StoryId,
  'expiresAt' : Timestamp,
  'authorId' : UserId,
  'mediaUrl' : IDL.Text,
});
export const ConversationId = IDL.Nat;
export const ConversationPreview = IDL.Record({
  'id' : ConversationId,
  'isOtherOnline' : IDL.Bool,
  'lastMessageAt' : IDL.Opt(Timestamp),
  'otherUsername' : IDL.Text,
  'otherUserId' : UserId,
  'otherProfilePic' : IDL.Text,
  'lastMessage' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'postCount' : IDL.Nat,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'isOnline' : IDL.Bool,
  'coverPhoto' : IDL.Text,
  'isPrivate' : IDL.Bool,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
  'profilePic' : IDL.Text,
});
export const FriendSuggestion = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'userId' : UserId,
  'mutualFollowers' : IDL.Nat,
  'profilePic' : IDL.Text,
});
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'conversationId' : ConversationId,
  'senderId' : UserId,
});
export const NotificationId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'like' : IDL.Null,
  'live' : IDL.Null,
  'comment' : IDL.Null,
  'follow' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : NotificationId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'type' : NotificationType,
  'isRead' : IDL.Bool,
  'actorId' : UserId,
  'entityId' : IDL.Nat,
});
export const Conversation = IDL.Record({
  'id' : ConversationId,
  'participants' : IDL.Vec(UserId),
  'lastMessageAt' : IDL.Opt(Timestamp),
  'lastMessage' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'createPost' : IDL.Func([CreatePostRequest], [Post], []),
  'createStory' : IDL.Func([IDL.Text, Timestamp], [Story], []),
  'follow' : IDL.Func([UserId], [IDL.Bool], []),
  'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(ConversationPreview)], ['query']),
  'getFeedPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserProfile)], ['query']),
  'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserProfile)], ['query']),
  'getFriendSuggestions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FriendSuggestion)],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [ConversationId, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyNotifications' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getReelById' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
  'getTrendingReels' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserStories' : IDL.Func([UserId], [IDL.Vec(Story)], ['query']),
  'isFollowing' : IDL.Func([UserId, UserId], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [IDL.Bool], []),
  'likeReel' : IDL.Func([PostId], [IDL.Bool], []),
  'markAllNotificationsRead' : IDL.Func([], [IDL.Nat], []),
  'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'sendMessage' : IDL.Func([ConversationId, IDL.Text], [Message], []),
  'setOnlineStatus' : IDL.Func([IDL.Bool], [], []),
  'shareReel' : IDL.Func([PostId], [IDL.Bool], []),
  'startConversation' : IDL.Func([UserId], [Conversation], []),
  'unfollow' : IDL.Func([UserId], [IDL.Bool], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostType = IDL.Variant({
    'reel' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const CreatePostRequest = IDL.Record({
    'content' : IDL.Text,
    'type' : PostType,
    'reelUrl' : IDL.Text,
    'imageUrl' : IDL.Text,
    'caption' : IDL.Text,
  });
  const PostId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Post = IDL.Record({
    'id' : PostId,
    'likeCount' : IDL.Nat,
    'content' : IDL.Text,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'type' : PostType,
    'reelUrl' : IDL.Text,
    'shareCount' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'caption' : IDL.Text,
    'commentCount' : IDL.Nat,
  });
  const StoryId = IDL.Nat;
  const Story = IDL.Record({
    'id' : StoryId,
    'expiresAt' : Timestamp,
    'authorId' : UserId,
    'mediaUrl' : IDL.Text,
  });
  const ConversationId = IDL.Nat;
  const ConversationPreview = IDL.Record({
    'id' : ConversationId,
    'isOtherOnline' : IDL.Bool,
    'lastMessageAt' : IDL.Opt(Timestamp),
    'otherUsername' : IDL.Text,
    'otherUserId' : UserId,
    'otherProfilePic' : IDL.Text,
    'lastMessage' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'postCount' : IDL.Nat,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'isOnline' : IDL.Bool,
    'coverPhoto' : IDL.Text,
    'isPrivate' : IDL.Bool,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
    'profilePic' : IDL.Text,
  });
  const FriendSuggestion = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'userId' : UserId,
    'mutualFollowers' : IDL.Nat,
    'profilePic' : IDL.Text,
  });
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'conversationId' : ConversationId,
    'senderId' : UserId,
  });
  const NotificationId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'like' : IDL.Null,
    'live' : IDL.Null,
    'comment' : IDL.Null,
    'follow' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : NotificationId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'type' : NotificationType,
    'isRead' : IDL.Bool,
    'actorId' : UserId,
    'entityId' : IDL.Nat,
  });
  const Conversation = IDL.Record({
    'id' : ConversationId,
    'participants' : IDL.Vec(UserId),
    'lastMessageAt' : IDL.Opt(Timestamp),
    'lastMessage' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'createPost' : IDL.Func([CreatePostRequest], [Post], []),
    'createStory' : IDL.Func([IDL.Text, Timestamp], [Story], []),
    'follow' : IDL.Func([UserId], [IDL.Bool], []),
    'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationPreview)],
        ['query'],
      ),
    'getFeedPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserProfile)], ['query']),
    'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserProfile)], ['query']),
    'getFriendSuggestions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FriendSuggestion)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [ConversationId, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyNotifications' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getReelById' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
    'getTrendingReels' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserStories' : IDL.Func([UserId], [IDL.Vec(Story)], ['query']),
    'isFollowing' : IDL.Func([UserId, UserId], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [IDL.Bool], []),
    'likeReel' : IDL.Func([PostId], [IDL.Bool], []),
    'markAllNotificationsRead' : IDL.Func([], [IDL.Nat], []),
    'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'sendMessage' : IDL.Func([ConversationId, IDL.Text], [Message], []),
    'setOnlineStatus' : IDL.Func([IDL.Bool], [], []),
    'shareReel' : IDL.Func([PostId], [IDL.Bool], []),
    'startConversation' : IDL.Func([UserId], [Conversation], []),
    'unfollow' : IDL.Func([UserId], [IDL.Bool], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };