/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Conversation {
  'id' : ConversationId,
  'participants' : Array<UserId>,
  'lastMessageAt' : [] | [Timestamp],
  'lastMessage' : [] | [string],
}
export type ConversationId = bigint;
export interface ConversationPreview {
  'id' : ConversationId,
  'isOtherOnline' : boolean,
  'lastMessageAt' : [] | [Timestamp],
  'otherUsername' : string,
  'otherUserId' : UserId,
  'otherProfilePic' : string,
  'lastMessage' : [] | [string],
}
export interface CreatePostRequest {
  'content' : string,
  'type' : PostType,
  'reelUrl' : string,
  'imageUrl' : string,
  'caption' : string,
}
export interface FriendSuggestion {
  'username' : string,
  'displayName' : string,
  'userId' : UserId,
  'mutualFollowers' : bigint,
  'profilePic' : string,
}
export interface Message {
  'id' : MessageId,
  'content' : string,
  'createdAt' : Timestamp,
  'conversationId' : ConversationId,
  'senderId' : UserId,
}
export type MessageId = bigint;
export interface Notification {
  'id' : NotificationId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'type' : NotificationType,
  'isRead' : boolean,
  'actorId' : UserId,
  'entityId' : bigint,
}
export type NotificationId = bigint;
export type NotificationType = { 'like' : null } |
  { 'live' : null } |
  { 'comment' : null } |
  { 'follow' : null };
export interface Post {
  'id' : PostId,
  'likeCount' : bigint,
  'content' : string,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'type' : PostType,
  'reelUrl' : string,
  'shareCount' : bigint,
  'imageUrl' : string,
  'caption' : string,
  'commentCount' : bigint,
}
export type PostId = bigint;
export type PostType = { 'reel' : null } |
  { 'text' : null } |
  { 'image' : null };
export interface Story {
  'id' : StoryId,
  'expiresAt' : Timestamp,
  'authorId' : UserId,
  'mediaUrl' : string,
}
export type StoryId = bigint;
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'postCount' : bigint,
  'username' : string,
  'displayName' : string,
  'isOnline' : boolean,
  'coverPhoto' : string,
  'isPrivate' : boolean,
  'followerCount' : bigint,
  'followingCount' : bigint,
  'profilePic' : string,
}
export interface _SERVICE {
  'createPost' : ActorMethod<[CreatePostRequest], Post>,
  'createStory' : ActorMethod<[string, Timestamp], Story>,
  'follow' : ActorMethod<[UserId], boolean>,
  'getActiveStories' : ActorMethod<[], Array<Story>>,
  'getConversations' : ActorMethod<[], Array<ConversationPreview>>,
  'getFeedPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getFollowers' : ActorMethod<[UserId], Array<UserProfile>>,
  'getFollowing' : ActorMethod<[UserId], Array<UserProfile>>,
  'getFriendSuggestions' : ActorMethod<[bigint], Array<FriendSuggestion>>,
  'getMessages' : ActorMethod<[ConversationId, bigint, bigint], Array<Message>>,
  'getMyNotifications' : ActorMethod<[bigint, bigint], Array<Notification>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getPost' : ActorMethod<[PostId], [] | [Post]>,
  'getProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getReelById' : ActorMethod<[PostId], [] | [Post]>,
  'getTrendingReels' : ActorMethod<[bigint], Array<Post>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserStories' : ActorMethod<[UserId], Array<Story>>,
  'isFollowing' : ActorMethod<[UserId, UserId], boolean>,
  'likePost' : ActorMethod<[PostId], boolean>,
  'likeReel' : ActorMethod<[PostId], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], bigint>,
  'markNotificationRead' : ActorMethod<[NotificationId], boolean>,
  'registerUser' : ActorMethod<[string, string], boolean>,
  'sendMessage' : ActorMethod<[ConversationId, string], Message>,
  'setOnlineStatus' : ActorMethod<[boolean], undefined>,
  'shareReel' : ActorMethod<[PostId], boolean>,
  'startConversation' : ActorMethod<[UserId], Conversation>,
  'unfollow' : ActorMethod<[UserId], boolean>,
  'updateProfile' : ActorMethod<
    [string, string, string, string, string, boolean],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];