/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface FriendSuggestion {
    username: string;
    displayName: string;
    userId: UserId;
    mutualFollowers: bigint;
    profilePic: string;
}
export type PostId = bigint;
export type StoryId = bigint;
export interface Story {
    id: StoryId;
    expiresAt: Timestamp;
    authorId: UserId;
    mediaUrl: string;
}
export interface ConversationPreview {
    id: ConversationId;
    isOtherOnline: boolean;
    lastMessageAt?: Timestamp;
    otherUsername: string;
    otherUserId: UserId;
    otherProfilePic: string;
    lastMessage?: string;
}
export type ConversationId = bigint;
export type UserId = Principal;
export type MessageId = bigint;
export interface Post {
    id: PostId;
    likeCount: bigint;
    content: string;
    authorId: UserId;
    createdAt: Timestamp;
    type: PostType;
    reelUrl: string;
    shareCount: bigint;
    imageUrl: string;
    caption: string;
    commentCount: bigint;
}
export type NotificationId = bigint;
export interface Notification {
    id: NotificationId;
    userId: UserId;
    createdAt: Timestamp;
    type: NotificationType;
    isRead: boolean;
    actorId: UserId;
    entityId: bigint;
}
export interface Message {
    id: MessageId;
    content: string;
    createdAt: Timestamp;
    conversationId: ConversationId;
    senderId: UserId;
}
export interface CreatePostRequest {
    content: string;
    type: PostType;
    reelUrl: string;
    imageUrl: string;
    caption: string;
}
export interface Conversation {
    id: ConversationId;
    participants: Array<UserId>;
    lastMessageAt?: Timestamp;
    lastMessage?: string;
}
export interface UserProfile {
    id: UserId;
    bio: string;
    postCount: bigint;
    username: string;
    displayName: string;
    isOnline: boolean;
    coverPhoto: string;
    isPrivate: boolean;
    followerCount: bigint;
    followingCount: bigint;
    profilePic: string;
}
export enum NotificationType {
    like = "like",
    live = "live",
    comment = "comment",
    follow = "follow"
}
export enum PostType {
    reel = "reel",
    text = "text",
    image = "image"
}
export interface backendInterface {
    createPost(req: CreatePostRequest): Promise<Post>;
    createStory(mediaUrl: string, expiresAt: Timestamp): Promise<Story>;
    follow(targetId: UserId): Promise<boolean>;
    getActiveStories(): Promise<Array<Story>>;
    getConversations(): Promise<Array<ConversationPreview>>;
    getFeedPosts(limit: bigint, offset: bigint): Promise<Array<Post>>;
    getFollowers(userId: UserId): Promise<Array<UserProfile>>;
    getFollowing(userId: UserId): Promise<Array<UserProfile>>;
    getFriendSuggestions(limit: bigint): Promise<Array<FriendSuggestion>>;
    getMessages(conversationId: ConversationId, limit: bigint, offset: bigint): Promise<Array<Message>>;
    getMyNotifications(limit: bigint, offset: bigint): Promise<Array<Notification>>;
    getMyProfile(): Promise<UserProfile | null>;
    getPost(postId: PostId): Promise<Post | null>;
    getProfile(userId: UserId): Promise<UserProfile | null>;
    getReelById(reelId: PostId): Promise<Post | null>;
    getTrendingReels(limit: bigint): Promise<Array<Post>>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserStories(userId: UserId): Promise<Array<Story>>;
    isFollowing(follower: UserId, followee: UserId): Promise<boolean>;
    likePost(postId: PostId): Promise<boolean>;
    likeReel(reelId: PostId): Promise<boolean>;
    markAllNotificationsRead(): Promise<bigint>;
    markNotificationRead(notificationId: NotificationId): Promise<boolean>;
    registerUser(username: string, displayName: string): Promise<boolean>;
    sendMessage(conversationId: ConversationId, content: string): Promise<Message>;
    setOnlineStatus(isOnline: boolean): Promise<void>;
    shareReel(reelId: PostId): Promise<boolean>;
    startConversation(otherUserId: UserId): Promise<Conversation>;
    unfollow(targetId: UserId): Promise<boolean>;
    updateProfile(username: string, displayName: string, bio: string, profilePic: string, coverPhoto: string, isPrivate: boolean): Promise<boolean>;
}
import type { Conversation as _Conversation, ConversationId as _ConversationId, ConversationPreview as _ConversationPreview, CreatePostRequest as _CreatePostRequest, Notification as _Notification, NotificationId as _NotificationId, NotificationType as _NotificationType, Post as _Post, PostId as _PostId, PostType as _PostType, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createPost(arg0: CreatePostRequest): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(to_candid_CreatePostRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Post_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(to_candid_CreatePostRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Post_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStory(arg0: string, arg1: Timestamp): Promise<Story> {
        if (this.processError) {
            try {
                const result = await this.actor.createStory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStory(arg0, arg1);
            return result;
        }
    }
    async follow(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.follow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.follow(arg0);
            return result;
        }
    }
    async getActiveStories(): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveStories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveStories();
            return result;
        }
    }
    async getConversations(): Promise<Array<ConversationPreview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedPosts(arg0: bigint, arg1: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedPosts(arg0, arg1);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedPosts(arg0, arg1);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowers(arg0: UserId): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getFollowing(arg0: UserId): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0);
            return result;
        }
    }
    async getFriendSuggestions(arg0: bigint): Promise<Array<FriendSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendSuggestions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendSuggestions(arg0);
            return result;
        }
    }
    async getMessages(arg0: ConversationId, arg1: bigint, arg2: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, arg1, arg2);
            return result;
        }
    }
    async getMyNotifications(arg0: bigint, arg1: bigint): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications(arg0, arg1);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications(arg0, arg1);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: PostId): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReelById(arg0: PostId): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReelById(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReelById(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingReels(arg0: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingReels(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingReels(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserStories(arg0: UserId): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStories(arg0);
            return result;
        }
    }
    async isFollowing(arg0: UserId, arg1: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0, arg1);
            return result;
        }
    }
    async likePost(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async likeReel(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likeReel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeReel(arg0);
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: NotificationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return result;
        }
    }
    async sendMessage(arg0: ConversationId, arg1: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async setOnlineStatus(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOnlineStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOnlineStatus(arg0);
            return result;
        }
    }
    async shareReel(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.shareReel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shareReel(arg0);
            return result;
        }
    }
    async startConversation(arg0: UserId): Promise<Conversation> {
        if (this.processError) {
            try {
                const result = await this.actor.startConversation(arg0);
                return from_candid_Conversation_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startConversation(arg0);
            return from_candid_Conversation_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async unfollow(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollow(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_ConversationPreview_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversationPreview): ConversationPreview {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Conversation_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Conversation): Conversation {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_PostType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostType): PostType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Post | null {
    return value.length === 0 ? null : from_candid_Post_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConversationId;
    isOtherOnline: boolean;
    lastMessageAt: [] | [_Timestamp];
    otherUsername: string;
    otherUserId: _UserId;
    otherProfilePic: string;
    lastMessage: [] | [string];
}): {
    id: ConversationId;
    isOtherOnline: boolean;
    lastMessageAt?: Timestamp;
    otherUsername: string;
    otherUserId: UserId;
    otherProfilePic: string;
    lastMessage?: string;
} {
    return {
        id: value.id,
        isOtherOnline: value.isOtherOnline,
        lastMessageAt: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.lastMessageAt)),
        otherUsername: value.otherUsername,
        otherUserId: value.otherUserId,
        otherProfilePic: value.otherProfilePic,
        lastMessage: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.lastMessage))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    userId: _UserId;
    createdAt: _Timestamp;
    type: _NotificationType;
    isRead: boolean;
    actorId: _UserId;
    entityId: bigint;
}): {
    id: NotificationId;
    userId: UserId;
    createdAt: Timestamp;
    type: NotificationType;
    isRead: boolean;
    actorId: UserId;
    entityId: bigint;
} {
    return {
        id: value.id,
        userId: value.userId,
        createdAt: value.createdAt,
        type: from_candid_NotificationType_n18(_uploadFile, _downloadFile, value.type),
        isRead: value.isRead,
        actorId: value.actorId,
        entityId: value.entityId
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConversationId;
    participants: Array<_UserId>;
    lastMessageAt: [] | [_Timestamp];
    lastMessage: [] | [string];
}): {
    id: ConversationId;
    participants: Array<UserId>;
    lastMessageAt?: Timestamp;
    lastMessage?: string;
} {
    return {
        id: value.id,
        participants: value.participants,
        lastMessageAt: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.lastMessageAt)),
        lastMessage: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.lastMessage))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PostId;
    likeCount: bigint;
    content: string;
    authorId: _UserId;
    createdAt: _Timestamp;
    type: _PostType;
    reelUrl: string;
    shareCount: bigint;
    imageUrl: string;
    caption: string;
    commentCount: bigint;
}): {
    id: PostId;
    likeCount: bigint;
    content: string;
    authorId: UserId;
    createdAt: Timestamp;
    type: PostType;
    reelUrl: string;
    shareCount: bigint;
    imageUrl: string;
    caption: string;
    commentCount: bigint;
} {
    return {
        id: value.id,
        likeCount: value.likeCount,
        content: value.content,
        authorId: value.authorId,
        createdAt: value.createdAt,
        type: from_candid_PostType_n7(_uploadFile, _downloadFile, value.type),
        reelUrl: value.reelUrl,
        shareCount: value.shareCount,
        imageUrl: value.imageUrl,
        caption: value.caption,
        commentCount: value.commentCount
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    like: null;
} | {
    live: null;
} | {
    comment: null;
} | {
    follow: null;
}): NotificationType {
    return "like" in value ? NotificationType.like : "live" in value ? NotificationType.live : "comment" in value ? NotificationType.comment : "follow" in value ? NotificationType.follow : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reel: null;
} | {
    text: null;
} | {
    image: null;
}): PostType {
    return "reel" in value ? PostType.reel : "text" in value ? PostType.text : "image" in value ? PostType.image : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConversationPreview>): Array<ConversationPreview> {
    return value.map((x)=>from_candid_ConversationPreview_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CreatePostRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePostRequest): _CreatePostRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PostType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostType): _PostType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    type: PostType;
    reelUrl: string;
    imageUrl: string;
    caption: string;
}): {
    content: string;
    type: _PostType;
    reelUrl: string;
    imageUrl: string;
    caption: string;
} {
    return {
        content: value.content,
        type: to_candid_PostType_n3(_uploadFile, _downloadFile, value.type),
        reelUrl: value.reelUrl,
        imageUrl: value.imageUrl,
        caption: value.caption
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostType): {
    reel: null;
} | {
    text: null;
} | {
    image: null;
} {
    return value == PostType.reel ? {
        reel: null
    } : value == PostType.text ? {
        text: null
    } : value == PostType.image ? {
        image: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
